"""Add assigned_manager and assigned_shift_type columns

Revision ID: 91c430ed1d10
Revises: c3a71a8584a4
Create Date: 2025-06-27 04:35:48.522685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c430ed1d10'
down_revision: Union[str, Sequence[str], None] = 'c3a71a8584a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
