"""Add sender and recipient columns

Revision ID: caf9e00ce332
Revises: 91c430ed1d10
Create Date: 2025-07-28 20:55:46.700210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf9e00ce332'
down_revision: Union[str, Sequence[str], None] = '91c430ed1d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',

    )
    # ### end Alembic commands ###
